### ISSUE TITLE
`lang` attribute

### ISSUE THREAD

**Issue by gojutin** [ifiokjr/gatsby-plugin-next-seo#14]
Thanks for this plugin, it's great. I don't see a prop for the `lang` attribute, which is resulting in a Lighthouse audit failure. Am I missing something or is this something you would consider adding if not? Thanks!

**Comment by ifiokjr** [comment]
Thanks for raising this. This is now added by bd0add9.

Add the `language` prop to your `GatsbySeo` component once the release is made available.

**Comment by gojutin** [comment]
Great thanks for the quick response!

**Comment by jayjayzheng** [comment]
from what I tested, this "language" prop is not working on current version. it's not being added to <html> at all.

any clue if this is taken out by any chance?

**Comment by ifiokjr** [comment]
Perhaps open a new issue?

**Comment by DevanB** [comment]
Can confirm that the `language` prop is not being set as `lang` (or as anything). 

This issue specifically targets the addition, and is so new that I'm wondering what the value of opening a new issue is...if the original implementation was flawed (it was never confirmed to be working by anyone after it was added in bd0add9).

**Comment by jayjayzheng** [comment]
not "language" and not "lang". 

I have to use <Helmet/> separately.

`      <Helmet
        htmlAttributes={{
          lang,
        }}
      />`

**Comment by DevanB** [comment]
Same here. Based on the source, `language` should be setting the HTML `lang` value, and it isn’t.

**Comment by ifiokjr** [comment]
Okay, I'll reopen. I'd be happy for someone else to take a look as I probably won't be able to for a few days.

**Comment by wlockiv** [comment]
@ifiokjr Could it be that the GatsbySeo component doesn't destructure the language prop? I would PR but I honestly have no idea how to test gatsby plugins without installing them via yarn/npm.
