### ISSUE TITLE
String outputting to Object in Open graph

### ISSUE THREAD

**Issue by shanejones** [ifiokjr/gatsby-plugin-next-seo#15]
I have the component outputting like so 

```
<GatsbySeo
  title={pageTitle}
  description={metaDescription}
  openGraph={{
    title: { pageTitle },
    description: { metaDescription },
    images: [
      {
        url: "https://domain.com/image.jpg",
        width: 1200,
        height: 630,
        alt: "Image Name",
      },
    ],
  }}
/>
```

The main title and description outputs fine here but the `og:title` and `og:description`  seem to be outputting [object Object]
![Screenshot 2020-05-08 at 12 24 55](https://user-images.githubusercontent.com/325424/81401314-fc8b6500-9126-11ea-9226-fa113efce1e9.jpg)

Any ideas why a string is being converted to an object and is there any way to stop that?

Thanks

**Comment by ifiokjr** [comment]
It's because you've wrapped the `title` and `description` in curly braces and it's being passed as an object when a string is expected. 

Let me know if the following changes fix it for you.

```diff
<GatsbySeo
  title={pageTitle}
  description={metaDescription}
  openGraph={{
-   title: { pageTitle },
+   title: pageTitle,
-   description: { metaDescription },
+   description: metaDescription,
    images: [
      {
        url: "https://domain.com/image.jpg",
        width: 1200,
        height: 630,
        alt: "Image Name",
      },
    ],
  }}
/>
```

**Comment by shanejones** [comment]
Ahh of course! All working fine now 

Thanks for a great plugin!
