### ISSUE TITLE
FAQJsonLD erroring

### ISSUE THREAD

**Issue by shanejones** [ifiokjr/gatsby-plugin-next-seo#18]
Just noticed what appears to be an error with FAQ Schema

To double-check it wasn't my markup I used your example code from within the repo

In my imports I have 
```
import { GatsbySeo, ArticleJsonLd, FAQJsonLd } from "gatsby-plugin-next-seo";
```

And in the main component block, I have
```
    <FAQJsonLd
      mainEntity={[
        { question: "What?", answer: "Stand" },
        { question: "How?", answer: "Effort" },
        { question: "Why?", answer: "Peace" },
      ]}
    />
```

The error I'm getting is `TypeError: can't access property "map", questions is undefined`

I have this in a component that also uses ArticleJsonLd and that is outputting fine on the page.

**Comment by ifiokjr** [comment]
Would you be comfortable creating a PR with a fix for this?

**Comment by shanejones** [comment]
Will have a dig around today. Not familiar with Gatsby plugins but this might be a good first contribution. 😁

**Comment by shanejones** [comment]
Right I've had a look and I've worked it out to be an issue with this block in `faq.js`

```
  var mainEntity = _ref2.questions,
      _ref2$overrides = _ref2.overrides,
      overrides = _ref2$overrides === void 0 ? {} : _ref2$overrides,
      _ref2$defer = _ref2.defer,
      defer = _ref2$defer === void 0 ? false : _ref2$defer;
```

When I console log `_ref2` it outputs the questions and answers,  when I console.log `mainEntity` it returns undefined.

I'm unsure what this block does and also unsure how to tweak this plugin as it appears to be in TypeScript.

**Comment by ifiokjr** [comment]
Thanks for looking into it. I'll make some time to provide a fix. This week is already full of deadlines, so maybe next week at the earliest.

**Comment by jayjayzheng** [comment]
change "mainEntity" to "questions" should just work

**Comment by shanejones** [comment]
Documentation PR submitted.

**Comment by ifiokjr** [comment]
Thanks @jayjayzheng and @shanejones! 😄
