### ISSUE TITLE
License is missing copyright notice

### ISSUE THREAD

**Issue by balibebas** [ifiokjr/gatsby-plugin-next-seo#20]
A condition of the MIT license is that the license text and the copyright notice must remain in derrivative copies. You should restore Gary's name since it looks like it was removed in https://github.com/ifiokjr/gatsby-plugin-next-seo/commit/094d3162bf07bfda338df708bea72d18cc993471

**Comment by ifiokjr** [comment]
@garmeeh what are your thoughts?

**Comment by balibebas** [comment]
Just to point out the license requirements are set in stone. Anything else would be a _crayon license_ and wouldn't be considered MIT anymore.

**Comment by ifiokjr** [comment]
Closing, please comment if you think this is premature.

**Comment by balibebas** [comment]
Please correct me if I'm wrong. But if I'm not mistaken [this commit](https://github.com/ifiokjr/gatsby-plugin-next-seo/commit/094d3162bf07bfda338df708bea72d18cc993471#r40047861) changed the copyright holder. Then the copyright holder was omitted entirely later. In order to square up your license you need to restore the original [copyright notice](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html#copyright-notice) and then add a copyright notice of your own. Without that it's not clear this may be an adapted work and, assuming it is, who the copyright holder(s) are.

To maximize the potential of individuals to benefit from open source software it's important the license is handled with care. If you're still using code from the original copyright holder they should still be named in the license with their original copyright notice.

**Comment by balibebas** [comment]
Please correct me if I'm wrong. But if I'm not mistaken [this commit](https://github.com/ifiokjr/gatsby-plugin-next-seo/commit/094d3162bf07bfda338df708bea72d18cc993471#r40047861) changed the copyright holder. Then the copyright holder was omitted entirely later. In order to square up your license you need to restore the original [copyright notice](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html#copyright-notice) and then add a copyright notice of your own. Without that it's not clear this may be an adapted work and, assuming it is, who the copyright holder(s) are.

**Comment by ifiokjr** [comment]
Feel free to open a PR, I'll happily merge it.

**Comment by balibebas** [comment]
> Feel free to open a PR, I'll happily merge it.

I'm offering guidance to the maintainer. I hope it has been helpful. It's not my place to make license changes to software projects I've not been an active contributor to. But one thing is certain and that's that this software needs a proper license in order to be most useful to the community. How you choose to handle that as at your discretion. Thanks for your ear.

**Comment by ifiokjr** [comment]
Okay when you have time, I'll merge your work.

**Comment by balibebas** [comment]
> Okay when you have time, I'll merge your work.

I think you may have misunderstood my message. I will not be submitting any fixes. I've given guidance. The code is still wrong. Please let me know if anything is unclear.
