### ISSUE TITLE
OpenGraph images are replacing & with &amp;

### ISSUE THREAD

**Issue by shanejones** [ifiokjr/gatsby-plugin-next-seo#23]
## Description

OpenGraph images are replacing `&` with `&amp;` when rendering through the plugin, this is causing the images to error on OpenGraph compatible sites. The Image url is formed fine before pushing into the plugin.

## Possible Fix

Stop turning `&` to `&amp;`

**Comment by Suganthan-Mohanadasan** [comment]
@ifiokjr Any chance when this will be fixed? Thanks so much for your help 👍

**Comment by wlockiv** [comment]
@shanejones I can't reproduce your issue. Would you please share some of your code, or provide a repo that suffers from this issue?

**Comment by shanejones** [comment]
@wlockiv  Will get something over to you shortly.

**Comment by Suganthan-Mohanadasan** [comment]
Thanks @shanejones

**Comment by shanejones** [comment]
Turns out the issue was on Twitters side, you need to force https or http on the image links.
