### ISSUE TITLE
OG tags don't render properly on LinkedIn

### ISSUE THREAD

**Issue by mcbergsma** [ifiokjr/gatsby-plugin-next-seo#25]
## Description

Using the plugin to optimize some links on LinkedIn, which used OG, but the previews don't show up. They look perfect in Slack (used for testing)

## Possible Fix

According to this [post](https://www.linkedin.com/pulse/how-generate-proper-link-previews-social-media-code-included-smith/), LinkedIn requires `prefix="og: http://ogp.me/ns#" to be included in the meta tag.

## Checklist

- ✔ I have read the [**contributing**](https://github.com/ifiokjr/gatsby-plugin-next-seo/blob/master/CONTRIBUTING.md) document.

**Comment by wlockiv** [comment]
@mcbergsma I noticed you closed the PR - is this still an issue for you?

**Comment by mcbergsma** [comment]
Still an issue! Closed the PR because I couldn't get it to work, first
attempt at making one - apologies!

------------------------------
*From:* wlockiv <notifications@github.com>
*Sent:* Friday, September 18, 2020 2:04:31 PM
*To:* ifiokjr/gatsby-plugin-next-seo <
gatsby-plugin-next-seo@noreply.github.com>
*Cc:* mcbergsma <mcbergsma@gmail.com>; Mention <mention@noreply.github.com>
*Subject:* Re: [ifiokjr/gatsby-plugin-next-seo] OG tags don't render
properly on LinkedIn (#25)


@mcbergsma <https://github.com/mcbergsma> I noticed you closed the PR - is
this still an issue for you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ifiokjr/gatsby-plugin-next-seo/issues/25#issuecomment-695009019>,
or unsubscribe

**Comment by dvzrd** [comment]
I'm trying a temp fix using the mediaTags prop, but it's not ideal:

```
metaTags: [
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:type",
        content: "article",
      },
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:title",
        content: seo?.title || title,
      },
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:description",
        content: seo?.description
          ? seo?.description
          : description
          ? description
          : excerpt,
      },
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:url",
        content: location?.href,
      },
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:image",
        content: `${location?.origin}${image?.childImageSharp?.fluid?.src}`,
      },
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:image:alt",
        content: seo?.title || title,
      },
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:image:width",
        content: "1200",
      },
      {
        prefix: "og: http://ogp.me/ns#",
        property: "og:image:height",
        content: "627",
      },
    ],
```

Any update on this issue? What happened to the PR? Was it failing a test or something?

**Comment by wlockiv** [comment]
Is there any reason why we can't make this prefix value default for all OpenGraph instead of introducing another prop?

**Comment by dvzrd** [comment]
> Is there any reason why we can't make this prefix value default for all OpenGraph instead of introducing another prop?

I thought it would be better to have the ability to add a prefix to the html tag instead of adding the prefix to every og metatag, but technically yes we can just hardcode the prefix to every og metatag instead like what was done in PR #26 

What do you think is the better alternative here? I would imagine the prefix value can change so it might be better to give more control to the dev to be able to update it when needed.

**Comment by wlockiv** [comment]
> > Is there any reason why we can't make this prefix value default for all OpenGraph instead of introducing another prop?
> 
> I thought it would be better to have the ability to add a prefix to the html tag instead of adding the prefix to every og metatag, but technically yes we can just hardcode the prefix to every og metatag instead like what was done in PR #26
> 
> What do you think is the better alternative here? I would imagine the prefix value can change so it might be better to give more control to the dev to be able to update it when needed.

So I did some more research and it looks like yours may be the appropriate method, especially considering how large of a refactor adding the prefix prop to each meta tag would be. 

I was confused a bit by some of the [conflicting information](https://stackoverflow.com/questions/48933419/opengraph-prefix-in-header-necessary#:~:text=1%20Answer&text=4-,prefix%3D%22og%3A%20http%3A%2F%2Fogp.me%2Fns,open%20graph%20protocol%20meta%20tags.&text=You%20can%20set%20it%20on,the%20scope%20of%20the%20prefix.) out there, and even how the OP mentioned that prefix must be in the meta tag... But it looks like [the og spec](https://ogp.me/) even recommends putting the prefix value in the `html` or `head` tags.

Please - Forgive my ignorance! 🙇🏼‍♂️

**Comment by dvzrd** [comment]
@wlockiv no worries, I'm pretty ignorant about this stuff also - thanks for doing the research and confirming these things. 

this is good to know, cheers! 🍻
