### ISSUE TITLE
Duplicate FAQ JSONLD schema

### ISSUE THREAD

**Issue by daydream05** [ifiokjr/gatsby-plugin-next-seo#28]
## Description

When you inspect element or view source, it only shows one FAQPage schema. But when deployed and tested using google's structured data tool, it shows that FAQ page is duplicated causing an error. 

Codesandbox replication:
https://codesandbox.io/s/duplicated-faq-rebfd

Deployed url:
https://csb-rebfd-omzyexojx.vercel.app/

Here's the structured data test where you can see it's duplicated.
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fcsb-rebfd-omzyexojx.vercel.app%2F

## Checklist

- [x] I have read the [**contributing**](https://github.com/ifiokjr/gatsby-plugin-next-seo/blob/master/CONTRIBUTING.md) document.

**Comment by ifiokjr** [comment]
If anyone wants to take a look at this I can partially assist

**Comment by daydream05** [comment]
I think the problem is with the tool. They've updated it now so I don't think there's any more issues going forward.

**Comment by ifiokjr** [comment]
Thanks for the update @daydream05
