### ISSUE TITLE
Provide a JSON-LD template for Google Sitelinks search box

### ISSUE THREAD

**Issue by Vacilando** [ifiokjr/gatsby-plugin-next-seo#29]
## Description

Could this project also provide a JSON-LD template for Google Sitelinks search box?
See https://developers.google.com/search/docs/data-types/sitelinks-searchbox#example

## Possible Implementation

Provide a JSON-LD template similar to that for Article, Blog, Product, etc.

## Checklist

- [x] I have read https://developers.google.com/search/docs/data-types/sitelinks-searchbox#example

**Comment by sternalouw** [comment]
Yes please. Also need that.

**Comment by ifiokjr** [comment]
Yeah that's definitely possible. 

I'm not currently using Gatsby, but I'm open to a PR.
