### ISSUE TITLE
Why is CorporateContactJsonLd deprecated ?

### ISSUE THREAD

**Issue by SimonKlausLudwig** [ifiokjr/gatsby-plugin-next-seo#39]
The Link seems to be broken. I can't find any source which tells that this field is deprecated https://developers.google.com/search/docs/data-types/corporate-contact ?

**Comment by ifiokjr** [comment]
At the time the documentation was written, the link led to a notice stating the deprecation. Google must have subsequently removed the link. 

The documentation is is no longer included in the list of [**Feature Guides**](https://developers.google.com/search/docs/data-types/article).

![image](https://user-images.githubusercontent.com/1160934/122171573-c6ff9200-ce77-11eb-8518-6959481a3b19.png)
