### ISSUE TITLE
WebpackError: No context yet created for the gatsby-plugin-next-seo

### ISSUE THREAD

**Issue by harlley** [ifiokjr/gatsby-plugin-next-seo#4]
## Description

Terminal shows this error message when I run `gastby develop`
`WebpackError: No context yet created for the gatsby-plugin-next-seo`

My pachage.json
```
{
  "name": "gatsby-starter-hello-world",
  "private": true,
  "description": "A simplified bare-bones starter for Gatsby",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "@emotion/core": "^10.0.27",
    "@emotion/styled": "^10.0.27",
    "@mdx-js/mdx": "^1.5.3",
    "@mdx-js/react": "^1.5.3",
    "bulma": "^0.8.0",
    "gatsby": "^2.18.18",
    "gatsby-mdx": "^1.0.0",
    "gatsby-plugin-google-analytics": "^2.1.31",
    "gatsby-plugin-mdx": "^1.0.64",
    "gatsby-plugin-mixpanel": "^3.1.2",
    "gatsby-plugin-next-seo": "^1.0.1",
    "gatsby-plugin-react-helmet": "^3.1.18",
    "gatsby-plugin-sass": "^2.1.26",
    "gatsby-source-filesystem": "^2.1.43",
    "gatsby-transformer-json": "^2.2.22",
    "node-sass": "^4.13.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1",
    "react-helmet-async": "^1.0.4"
  },
  "devDependencies": {
    "prettier": "^1.19.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

## Checklist

- [x] I have read the [**contributing**](https://github.com/ifiokjr/gatsby-plugin-next-seo/blob/master/CONTRIBUTING.md) document.

**Comment by ifiokjr** [comment]
Thanks for trying out the project. Have you installed `react-helmet-async`? That's the only reason I can think of for this happening.

I've made it a peer dependency because it relies on context as explained in the **setup** section of the [readme](https://github.com/ifiokjr/gatsby-plugin-next-seo#setup).

**Comment by ifiokjr** [comment]
@harlley disregard my last comment as I can see from your package.json that you have. Have you [added](https://github.com/ifiokjr/gatsby-plugin-next-seo#add-plugin-to-gatsby-config) it to your `gatsby-config.json`?

**Comment by harlley** [comment]
Yes, I added it to `gatsby-config.js`
This is my repo `https://github.com/harlley/playcode.com.br`

**Comment by ifiokjr** [comment]
Thanks @harlley I've managed to replicate. I'm looking into it now.

**Comment by ifiokjr** [comment]
@all-contributors please add @harlley raising an important bug.
