### ISSUE TITLE
Allow gatsby@next as a supported gatsby version

### ISSUE THREAD

**Issue by DeathCamel58** [ifiokjr/gatsby-plugin-next-seo#68]
When migrating my site to gatsby 4.0.0-zz-next.1, this plugin wont install due to the peer dependency being [`^2.0.0 || ^3.0.0`](https://github.com/ifiokjr/gatsby-plugin-next-seo/blob/54538a643659ea7885d759b0d7325d36db2d0057/package.json#L173).
Please also allow `^4.0.0` as a peer dependency.

**Comment by ifiokjr** [comment]
Fixed in #70
